### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Justinezgh** [Justinezgh/SBI-Diff-Simulator#30]
### **Study**

- [ ] Impact of gradient complexity
- [ ] How to tune lambda 
- [ ] How to use gradients in sequential methods

### **Implementation**

- [ ] Tasks 
  - [ ] Lotka Volterra
  - [ ] Galton Board 
  - [ ] Lensing
- [ ] Sequential methods 
  - [ ] SNLE
  - [ ] APT 
 - [ ] Automatisation notebook
